name: Create Lichess Tournaments Daily

on:
  schedule:
    - cron: "30 6 * * *"  # runs at 12:00 PM IST (6:30 AM UTC)
  workflow_dispatch:      # allows manual run from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 📦 Install dependencies
        run: |
          pip install requests pytz

      - name: 🔐 Inject Lichess API token
        run: |
          sed -i "s/API_TOKEN = .*/API_TOKEN = '${{ secrets.LICHESS_TOKEN }}'/" Tmt.py

      - name: 🚀 Run tournament creator
        run: python Tmt.py
